generic-service:
  nameOverride: james-kotlin-test
  productId: "DPS9999" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/james-kotlin-test
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: james-kotlin-test-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    JAVA_TOOL_OPTIONS: "-Dhttp.proxyHost=envoy-https-proxy -Dhttp.proxyPort=3128 -Dhttps.proxyHost=envoy-https-proxy -Dhttps.proxyPort=3128 -Dhttp.nonProxyHosts=localhost|127.*|envoy-https-proxy|*.svc|*.cluster.local -Dhttps.nonProxyHosts=localhost|127.*|envoy-https-proxy|*.svc|*.cluster.local -XX:+ExitOnOutOfMemoryError -XX:MaxRAMPercentage=50.0"
    HTTP_PROXY: "http://envoy-https-proxy:3128"
    HTTPS_PROXY: "http://envoy-https-proxy:3128"
    NO_PROXY: "localhost,127.0.0.1,envoy-https-proxy,.svc,.cluster.local"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    james-kotlin-test-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: james-kotlin-test
  
