name: Backup Repository to SharePoint

on:
  workflow_dispatch:      # Allow manual trigger

jobs:
  backup:
    name: Backup to SharePoint
    runs-on: ubuntu-latest
    steps:
      - name: Backup repository to SharePoint
        uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/sharepoint_repository_backup@feat/HEAT-966
        with:
          sharepoint_site_url: ${{ secrets.SHAREPOINT_SITE_URL }}
          sharepoint_folder_server_relative_url: ${{ secrets.SHAREPOINT_FOLDER_SERVER_RELATIVE_URL }}
          sharepoint_client_id: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          sharepoint_client_secret: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          retention_count: 5   # optional, defaults to 5
