name: Test token value
on:
  push:
    branches:
      - '**'

jobs:
  derive-token-suffix:
    runs-on: ubuntu-latest
    steps:
      - name: Derive token suffix for display
        shell: bash
        env:
          token: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
          sre_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
        run: |
          suffix="${token: -4}"
          echo "NON_SRE_SLACK_TOKEN_SUFFIX=****${suffix}" >> "$GITHUB_ENV"

          suffix="${sre_token: -4}"
          echo "SRE_SLACK_TOKEN_SUFFIX=****${suffix}" >> "$GITHUB_ENV"
